### ISSUE TITLE
[iOS] Dragging down the notification center or the quick settings triggers authentication

### ISSUE THREAD

**Issue by mvaivre** [alephium/mobile-wallet#119]
It seems like dragging down the notification center or the quick settings in iOS is considered as putting the app in the background and hence triggers authentication. This should not be the case IMO.

**Comment by nop33** [comment]
Wow, that's... annoying

**Comment by nop33** [comment]
Fixed! I just needed to read the docs better 😆 https://reactnative.dev/docs/0.69/appstate
