### ISSUE TITLE
Choose app name

### ISSUE THREAD

**Issue by nop33** [alephium/mobile-wallet#178]
Currently, our app is named `mobile-wallet` (defined in `app.json`: https://github.com/alephium/mobile-wallet/blob/master/app.json#L3).

Shouldn't we call it something else? How about simply "Alephium"? "Alephium wallet" might be a bit too long and "Alephium mobile wallet" even longer. Other ideas?

**Comment by mvaivre** [comment]
I'd be in favour of Alephium Wallet
