### ISSUE TITLE
Navigation refinements

### ISSUE THREAD

**Issue by mvaivre** [alephium/mobile-wallet#182]
# Bottom modals

Bottom modal can be a pain in the 🍑 . Why?

- When the content is scrollable, they can't be dismissed easily by scrolling down
- On iOS, users can't swipe from the side in order to go back
- They waste a bit of vertical screen estate.

To improve on this we could:

- Use less modals and more traditional screens (with back arrow and ability to swipe from the side to go back.
- Improve our bottom modal to make them really adapted to quick glances situation. Take a look at what artefact is doing. It's a great implementation for short content IMO, like TX details (but in the video it's used in a situation where a traditional screen would be more useful :P). The modal has 2 states: it first opens until half of the screen, allowing for a quick close gesture with the thumb. Swipping it up makes it go full screen. Content can be scrolled up and down. When scrolled all the way to the top, a down gesture closes the modal. It's quite intuitive. 
- Mix up both options above

Implementing the 2 states modal may be challenging and could be done in a later iteration. However, it would be great to find a way to allow closing the modal by swiping down from anywhere (once content can't be scrolled up anymore).

https://github.com/alephium/mobile-wallet/assets/6715943/8a1be5b4-e9d1-4a0d-8fa8-15db7f04d417

# Misc

Linking a traditional from a bottom modal causes issues: 
- The status bar color changes when opening a bottom modal
- ... but it stays the same color when navigating to a traditional screen.
- Going back and forth between these 2 kinds of screens causes glitches (vertical jumps)

**Comment by nop33** [comment]
> When the content is scrollable, they can't be dismissed easily by scrolling down

I've figured out a way to improve this. When the `ScrollView` is not long enough (when no scrolling is needed to see all its content), the screen can be swipped down from anywhere (see video for before and after).


https://github.com/alephium/mobile-wallet/assets/1579899/26a54049-6e92-4154-a642-bcc07d4764d7



> When scrolled all the way to the top, a down gesture closes the modal. It's quite intuitive.

This is a problem that still remains. When the `ScrollView` is long enough (meaning that scrolling is needed to see all its content) then when reaching the top we still cannot close the modal by swiping down.

**Comment by nop33** [comment]
This is what we want (unfortunately this is a different library than the one we are using) https://github.com/react-native-modal/react-native-modal/issues/109#issuecomment-379274368

**Comment by nop33** [comment]
This seems pretty cool: https://twitter.com/mosdnk/status/1233097798251425795

**Comment by nop33** [comment]
This article describes our problem exactly. It's a bit old so I don't know if that's the latest state of things.

https://medium.com/@iamdavidmartin/react-native-navigation-gestures-could-become-a-major-problem-on-ios-13-5180d02a3cc8

**Comment by mvaivre** [comment]
I've researched for more simple alternatives and stumbled upon this one: https://github.com/jeremybarbet/react-native-modalize. It's been last updated a year ago, but seeing the number of stars, it may be a good candidate anyway. 

Regarding the list of screens you described, I agree with most of them, BUT some cause issues as mentioned in my initial message. For instance, clicking on an action to create a wallet from the SwitchWalletScreen opens a traditional screen which messes up with the SatusBar. Going back at that point causes UI glitches.

**Comment by nop33** [comment]
> I've researched for more simple alternatives and stumbled upon this one: https://github.com/jeremybarbet/react-native-modalize. It's been last updated a year ago, but seeing the number of stars, it may be a good candidate anyway.

Cool, I saw this mentioned in the article I posted above:

> https://github.com/react-navigation/stack (the new 2.0 alpha version. note that only the top header is swipable)
> https://github.com/osdnk/react-native-reanimated-bottom-sheet (check out the map implementation)
> 👉  https://github.com/jeremybarbet/react-native-modalize (note that only the top header is swipable)
> https://github.com/react-native-community/react-native-modal

**Comment by nop33** [comment]
> For instance, clicking on an action to create a wallet from the SwitchWalletScreen opens a traditional screen which messes up with the SatusBar. Going back at that point causes UI glitches

You mean this glitch, right? In such case I agree, we could convert the `SwitchWalletScreen` to a normal one.

https://github.com/alephium/mobile-wallet/assets/1579899/098895a9-d376-4e25-b6a6-bf4850ec7b50

@mvaivre Shall I proceed with converting the screens, or leave it up to you to experiment with the `react-native-modalize` (or any other lib), or shall I experiment?

**Comment by nop33** [comment]
@mvaivre Shall we close this one since we have all other more specific issues open?

**Comment by mvaivre** [comment]
Yes, let's close this
