### ISSUE TITLE
Investigate: the whole Dashboard is remounted on app launch 

### ISSUE THREAD

**Issue by mvaivre** [alephium/mobile-wallet#197]
All the components seem to be remounted (new refs), which can cause unwanted side effects.
To be investigated.

**Comment by nop33** [comment]
Could be that something changes in the contexts that wrap the whole app.

**Comment by mvaivre** [comment]
Yeah probably.

**Comment by nop33** [comment]
Could you please provide some more info on how to reproduce this? I haven't noticed any glitches due to this.

**Comment by nop33** [comment]
I could not reproduce this. I added the following `useEffect` which should run on every mount. It was only executed once.

```ts
  useEffect(() => {
    console.log('Should run only once')
  }, [])
```
