### ISSUE TITLE
Create custom Pressable component displaying tap visual feedback

### ISSUE THREAD

**Issue by mvaivre** [alephium/mobile-wallet#200]
When using classic Pressable components, there's no visual feedback when interacting.
Let's override the Pressable component and implement visual feedback by default.

**Comment by nop33** [comment]
That's surprising... Reading the docs of `TouchableWithoutFeedback` I see that they recommend using `Pressable` for the reason that _"All elements that respond to press should have a visual feedback when touched"_...

https://reactnative.dev/docs/touchablewithoutfeedback

**Comment by mvaivre** [comment]
I meant: let's use the `Pressable` component to create a `AppPressable` one (name TBD), which embeds visual feedback (the naked `Pressable` don't display any feedback).

**Comment by nop33** [comment]
@mvaivre is this still relevant? If so, feel free to move it to the frontend repo by clicking "-> Transfer issue" on the right bottom side of this page.
