### ISSUE TITLE
Simplify the BalanceSummary for empty wallets

### ISSUE THREAD

**Issue by mvaivre** [alephium/mobile-wallet#214]
For now it looks like this: 

![image](https://github.com/alephium/mobile-wallet/assets/6715943/7d7c9878-48ad-4ee8-9f7c-abcc3fc95858)

Let's remove the delta, timeframe buttons, and chart area.

Let's also hide the send button, and only keep a "Receive funds" button.

**Comment by nop33** [comment]
There's a simpler layout now merged. Closing.

<img width="382" alt="image" src="https://github.com/alephium/mobile-wallet/assets/1579899/295bc9a5-2e11-4512-9f99-50443812ec7d">
