### ISSUE TITLE
Init testing

### ISSUE THREAD

**Issue by mvaivre** [alephium/mobile-wallet#23]
As discussed in #20 

> @tdroxler has taken a look at https://github.com/ex3ndr/react-native-fast-pbkdf2. 
> The annoying thing about this lib is the lack of tests on their side. Let's maybe take this "opportunity" to think about testing in this project and start implementing some.
>
> We could:
> 1) Use https://github.com/wix/Detox or Appium to automate some UI tests built around the use of native modules
> 2) Fork and add tests to the `fast-pbkdf2` library
> 3) Open a PR in the fore-mentioned library's repo.
>
> In any case, looking at scenario 1) seems interesting. We could use BrowserStack to make those tests run on many diff devices easily.
>
> WDYT?

**Comment by nop33** [comment]
Closing in favor of https://github.com/alephium/alephium-frontend/issues/70
