### ISSUE TITLE
Backup strategy improvements

### ISSUE THREAD

**Issue by mvaivre** [alephium/mobile-wallet#230]
This could eventually be split into multiple standalone issues.

- [x] Add a verification step. To make the process less painful, for each word to verify the user can choose between 3 words displayed on the screen.
- [x] Until the user verified the words, continue to show the ⚠️ icon highlighted in red. Hide the icon in the header once the verification step is done
- [x] Add an action in the settings to view the recovery phrase (protected by biometrics or the pin)

**Comment by nop33** [comment]
Would the verification step be part of the wallet creation flow, or part of the Security screen? (is it something the user needs to trigger once the wallet has already been created basically?) From what I understand by reading the comment above, it's the second case.

**Comment by mvaivre** [comment]
Yes second case. The idea is still to allow for a super fast onboarding, while still pressing the user to backup their words (but as a later step)
