### ISSUE TITLE
Improve password modal after qr code scan import

### ISSUE THREAD

**Issue by nop33** [alephium/mobile-wallet#246]
Currently, this is how the screen looks like.

We should:
- Add a close button on the top right
- Fix margins
- Make sure the keyboard is avoided
- Add some helping text

@mvaivre WDYT?

<img width="561" alt="image" src="https://github.com/alephium/mobile-wallet/assets/1579899/247de220-e031-4b56-9521-6fd1437c160d">

**Comment by mvaivre** [comment]
Absolutely ! 

1) Header nav buttons (back and next)
2) Title (in header)
3) Short explanation (like in other screens)
4) Keyboard avoidance.
