### ISSUE TITLE
Hide the screen content when app is in the background

### ISSUE THREAD

**Issue by mvaivre** [alephium/mobile-wallet#251]
... and until when FaceID managed to authenticate the user. 

I seem to remember a special function (in expo?), to hide the screen when in the background.

**Comment by nop33** [comment]
> I seem to remember a special function (in expo?), to hide the screen when in the background.

Can't seem to find something...

I found these instead:
- https://stackoverflow.com/questions/52558904/how-to-hide-current-screen-when-app-goes-background-in-react-native-android
- https://github.com/facebook/react-native/issues/34157
- https://github.com/euthribeiro/react-native-background-secure

**Comment by nop33** [comment]
So, by accident, while i was integrating the `expo-screen-capture` to solve https://github.com/alephium/mobile-wallet/issues/252 I noticed that when I move the app to the bg WHILE the mnemonic modal is shown, Android will immediately hide the screen. Which is great!

Questions:
- Do we really wanna hide the contents of EVERY screen when the app goes to the bg? Why not just hide the screens with sensitive info?
- If we prevent screenshots throughout our whole app, then this will as well hide every screen when the app goes to bg. Do we want that?
  - I could not find a way to ONLY hide the screen when app goes to bg but still allow screenshots.

**Comment by nop33** [comment]
My take is that as long as we are not leaking any sensitive info (mnemonic is hidden in every case) and since we require authentication when the app becomes active again, we don't need to hide the contents of every screen when the app goes to the bg.

**Comment by mvaivre** [comment]
Agreed.
