### ISSUE TITLE
Autofocus in DecryptScannedMnemonicScreen is not working properly

### ISSUE THREAD

**Issue by nop33** [alephium/mobile-wallet#255]
> here’s what I get after scanning the QR codes during import. Seems like the height is adapted to account for the keyboard… but the keyboard isn’t here haha. Tapping on the input makes the keyboard appear and the it’s fine.
Seems like the autofocus isn’t working properly.

![image](https://github.com/alephium/mobile-wallet/assets/1579899/c49d5536-bb46-4ae3-8089-0cfba1fd7cdb)

**Comment by nop33** [comment]
I can't seem to be able to reproduce this on the simulator. @mvaivre would you mind taking it over? To avoid scanning from the desktop wallet while debugging, you can simply change this line:

```diff
diff --git a/src/screens/new-wallet/SelectImportMethodScreen.tsx b/src/screens/new-wallet/SelectImportMethodScreen.tsx
index ff2ef2b..6edeed3 100644
--- a/src/screens/new-wallet/SelectImportMethodScreen.tsx
+++ b/src/screens/new-wallet/SelectImportMethodScreen.tsx
@@ -88,7 +88,7 @@ const SelectImportMethodScreen = ({ navigation, ...props }: SelectImportMethodSc
           <Button
             variant="highlight"
             title="Type your secret phrase"
-            onPress={() => navigation.navigate('ImportWalletSeedScreen')}
+            onPress={() => navigation.navigate('DecryptScannedMnemonicScreen')}
           />
         </BoxSurfaceStyled>
       </ScreenSection>
```



![Image](https://github.com/alephium/mobile-wallet/assets/1579899/68bffb91-627a-4463-a766-5a8ca42a2aed)

**Comment by mvaivre** [comment]
Oooof that is a super weird one. Could identify the root cause. Might be linked to the unmounting of the scan modal, potentially a super rare edge case.

I forced the focus (and prevented the blur) of the input in this (ugly?) commit: 249fd8b71e14364c08fd0b5c506a995c51170a8d

**Comment by nop33** [comment]
This is now solved.
