### ISSUE TITLE
[Biometrics] Improve Face ID permission mgmt

### ISSUE THREAD

**Issue by mvaivre** [alephium/mobile-wallet#258]
As of now, when creating a wallet, when the user decides to activate biometrics (at least for FaceID on iOS), no permission prompt is shown, and a FaceID scan isn't triggered right away.

When putting the app in the background then active again, the authorisation prompt is finally shown.

Problem: if at that point the user refuses to activate FaceID, then the option to activate it in the settings isn't available, and we won't ask for the permission when the user creates other wallets. The only way to fix this is to go into the OS settings and manually give the permission there.

IMO, a better way to go about it would be:

1) Show the permission prompt right when the user creates a wallet
2) Keep the option visible in the settings so that the user can activate biometrics later on.
3) Even if biometrics were refused once, keep asking the user they create a new wallet.

Please don't hesitate to share your thoughts! @nop33

**Comment by nop33** [comment]
> Show the permission prompt right when the user creates a wallet

What exactly is the permission prompt? Something like a dialog that says "allow this app to use your biometrics"? I don't remember seeing such a prompt on Android... I remember seeing for accessing the camera though.

> Problem: if at that point the user refuses to activate FaceID, then the option to activate it in the settings isn't available, and we won't ask for the permission when the user creates other wallets.
> ...
> Keep the option visible in the settings so that the user can activate biometrics later on.


This is a problem indeed. The biometrics settings should be toggle-able in the Settings page, no matter if the user activated them in the wallet creation flow or not. This is the case for fingerprint on Android. The code that shows/hides the biometrics settings basically checks:

> whether the device has saved fingerprints or facial data to use for authentication

```ts
import { isEnrolledAsync } from 'expo-local-authentication'
const available = await isEnrolledAsync()
```

https://docs.expo.dev/versions/latest/sdk/local-authentication/

> Even if biometrics were refused once, keep asking the user they create a new wallet.

Currently, we assume the preference of the user to enable biometrics by looking at the auth settings of the current wallet. We don't navigate to the `AddBiometricsScreen` anymore. We either enable them if the last wallet also had them or not:

```ts
if (lastActiveWalletAuthType.current === 'biometrics' && hasAvailableBiometrics) enableBiometrics(...)
```

This makes creation of additional wallets faster. But we can change our approach. Not sure what's best. On one side the wallet creation is faster. On the other side, we promote better security if we ask every time we notice that the user only uses pin to authenticate.

**Comment by mvaivre** [comment]
I made sure to force the display of the permission prompt in iOS by trying to read the encrypted mnemonic right away. See here: 89d4e2040cf5591e054a0e8909f9140933cecd8f

WDYT @nop33 ?

**Comment by nop33** [comment]
Great idea! As we discussed last night, we should test this on Android because I suspect it will ask for fingerprint twice. We could check `if (Platform.OS === 'ios')` and only then try to read right after writing.
