### ISSUE TITLE
[Android] Fix dimensions of landing screen

### ISSUE THREAD

**Issue by nop33** [alephium/mobile-wallet#271]
![image](https://github.com/alephium/mobile-wallet/assets/1579899/1aedab7c-755b-40ea-b351-6239730886b3)

**Comment by polarker** [comment]
Nitpicking: Let's not say that it's *official* )

**Comment by nop33** [comment]
@polarker Thanks for the feedback! I am wondering what else we could use then to signal that this wallet is developer by the team...

**Comment by polarker** [comment]
I don't know to be honest. It's not the tradition to have a so-called official wallet for a blockchain project. @mvaivre might have some ideas.

**Comment by mvaivre** [comment]
Yeah I asked myself the same question.

I think I'd go for something simple: "Welcome to your Alephium Wallet"

**Comment by polarker** [comment]
It could also be as simple as "Welcome to Alephium" since wallet is being used in the button content.
