### ISSUE TITLE
Link to correct FAQ entries

### ISSUE THREAD

**Issue by nop33** [alephium/mobile-wallet#273]
We currently have the following links, all leading to the FAQ page, but not to a particular entry:

| New wallet | Import wallet | Pin creation | Backup | Pin auth |
| ------         | ------------ | ------------   | ------- | -------- |
| <img width="565" alt="image" src="https://github.com/alephium/mobile-wallet/assets/1579899/699e97af-8fb6-4a9c-a14f-088f1f267e21"> | <img width="565" alt="image" src="https://github.com/alephium/mobile-wallet/assets/1579899/087ca3bf-0629-4f25-ad62-9a0eb71e8535"> | <img width="565" alt="image" src="https://github.com/alephium/mobile-wallet/assets/1579899/f13035f8-13dd-4a24-8027-a1711826d5d8"> | <img width="565" alt="image" src="https://github.com/alephium/mobile-wallet/assets/1579899/c3de407d-9657-4cb8-abb3-ded77d86659d"> | <img width="565" alt="image" src="https://github.com/alephium/mobile-wallet/assets/1579899/f17ae5c7-8071-4a39-8455-c7bacb145b9b"> |

Add correct links:
- [ ] New wallet
- [ ] Import wallet
- [ ] Pin creation
- [ ] Backup
- [ ] Pin auth

**Comment by nop33** [comment]
@mvaivre do you think we rly need links for all these screens? I'd say definitely yes for:
- Backup

Not so sure about the rest. Pin is a pretty standard thing to have in an app. Create/Import a wallet, not sure what we want to link to.

**Comment by mvaivre** [comment]
yeah let's go for the most simple solution, and only keep the link for the backup 🙏 

Thanks a lot for raising this.
