### ISSUE TITLE
Even Moar UI Improvements

### ISSUE THREAD

**Issue by mvaivre** [alephium/mobile-wallet#286]
- [x] "Default group" => "Random group"
- [x] Try using 2 colours again for send / receive buttons?
- [x] Try finding a clearer Settings grouping structure
- [x] In transfers list, use the same color for the TX Icon and the amounts.
- [x] Add assets number in tabs?
- [x] New tab design for light theme
- [ ] Fix receive assets button visible on load

Optional (create separate issues?)
- [ ] Make the import by QR code more visible from the get go (safest and most innovative function)
- [ ] Do something cool with the Alephium rainbow logo

**Comment by nop33** [comment]
>  Fix receive assets button visible on load

>  Do something cool with the Alephium rainbow logo

Both of these are done, right?

**Comment by nop33** [comment]
@mvaivre does this issue need to remain open and in the initial release milestone?

**Comment by mvaivre** [comment]
Nope! We're done.
