### ISSUE TITLE
Create beta release

### ISSUE THREAD

**Issue by nop33** [alephium/mobile-wallet#293]
Now that we figured out how to submit our internal testing release to Google Play and App Store (see https://github.com/alephium/mobile-wallet/issues/186), we need to figure out how to submit a beta release.

### Add preview assets
Based on: https://support.google.com/googleplay/android-developer/answer/9866151#zippy=%2Capp-icon
- [x] Name
- [x] Short description
- [x] Full description
- [x] App icon
- [x] Feature graphic
- [x] Phone screenshots (Upload 2-8 phone screenshots. Screenshots must be PNG or JPEG, up to 8 MB each, 16:9 or 9:16 aspect ratio, with each side between 320 px and 3,840 px. To be eligible for promotion, include at least 4 screenshots at a minimum of 1080 px on each side.)
- [x] 7-inch tablet screenshots (Upload up to eight 7-inch tablet screenshots. Screenshots must be PNG or JPEG, up to 8 MB each, 16:9 or 9:16 aspect ratio, with each side between 320 px and 3,840 px)
- [x] 10-inch tablet screenshots (Upload up to eight 10-inch tablet screenshots. Screenshots must be PNG or JPEG, up to 8 MB each, 16:9 or 9:16 aspect ratio, with each side between 1,080 px and 7,680 px)
- [x] build app
- [x] submit another internal testing release
- [x] promote internal testing release to open testing release
- [x] wait for review approval

## Apple

https://docs.expo.dev/submit/ios/

- [x] Build the app with `eas build --platform ios`
- [x] Submit it with `eas submit --platform ios`
- [x] Ensure that your app exists on App Store Connect and its [Bundle Identifier](https://expo.fyi/bundle-identifier) is registered on Apple Developer Portal
- [x] Ensure you have the proper credentials set up.
- [x] Submit binary
- [x] Copy summary of submitted info
- [x] Wait for Apple to review the app before TestFlight public link becomes available
- [x] Share with community

**Comment by nop33** [comment]
On Google, after the "internal testing", the next step sounds like it should be the "open testing": https://play.google.com/console/about/opentesting/

**Comment by nop33** [comment]
Example of text other apps are using:

<details><summary>🦊 Metamask </summary>

### Title
> MetaMask - Blockchain Wallet

### Short description
> A secure wallet & gateway to blockchain sites

### Full description
> Whether you are an experienced user or brand new to blockchain, MetaMask helps you connect to the decentralized web: a new internet.
> 
> We're trusted by millions of people across the world, and our mission is to make this new decentralized web accessible to all.
> 
> The MetaMask app is both a wallet & a browser. Buy, send, spend & exchange your digital assets. Make payments to anyone, anywhere. Log into websites securely to trade assets, lend, borrow, play games, publish content, buy rare digital art, and so much more.
> 
> With MetaMask, your keys and assets always stay in your control;
> • Use MetaMask’s key vault, secure login and digital wallet to manage your digital assets.
> • Generate passwords and keys on your phone and keep your accounts secure.
> • Browse and connect to the decentralized web sites.
> • Control what information you share with the sites you use, and what to keep private.
>
> If you’re already a MetaMask desktop user, you can import your existing wallet. If you're a new user, we'll help you get setup!
> 
> Download MetaMask Mobile and carry the decentralized web with you, wherever you go.
>
> Our privacy policy: https://consensys.net/privacy-policy/
> Terms of use: https://consensys.net/terms-of-use/

</details>

<details><summary> 🌈 Rainbow </summary>

### Title
> Rainbow Ethereum Wallet

### Short description
> Rainbow is a fun, simple, and secure way to get started with crypto.

### Full description
> Rainbow is a fun, simple, and secure way to get started with crypto and explore Ethereum. You can use Rainbow to purchase, manage, and display Ethereum-based assets on mainnet, Optimism, Arbitrum, Polygon, Base, and Zora.
> 
> Great for newcomers and power users alike, Rainbow allows you to be in total control of your money. Unlike a crypto exchange such as Coinbase, Rainbow doesn't hold your assets on your behalf. You own them directly thanks to the power of cryptography and the Ethereum blockchain.
> 
> You can instantly send, receive, and trade assets from your crypto wallet whenever you want without having to worry that your funds might be held by a financial institution.
> 
> Rainbow is open source and an active member of the Ethereum community, making us one of the ecosystem's most well-loved and trusted wallets.
> 
> With Rainbow, you can...
> 
> - Securely swap and bridge any token
> - Buy crypto and onboard directly into L2s
> - Bring your own wallet by importing your seed phrase from MetaMask and other wallets
> - Watch wallets and follow any public Ethereum address
> - Full transaction history and token discovery
> - Multiple wallet support and a way to quickly switch between them
> - Built-in Flashbots Protect safety on your Ethereum trades
> - Customizable real-time notifications for wallet activity
> - Find helpful articles, trending tokens, and new assets in the Discover section
> - Display crypto art from places like Zora, Foundation, OpenSea and Rarible
> - Claim your ENS username and carry it with you across Web3
> - Create and update your ENS Profile with your profile picture, social handles and links
> - Use WalletConnect to connect to decentralized apps and websites like Uniswap, OpenSea, Mirror, Aave and more
> - Showcase your favorite digital art on social media by sharing your Rainbow web profile
> - A beautiful interface and design that makes Web3 and crypto a joy
> - Send/receive assets to ENS usernames instead of long addresses
> - Robust digital art support including 3D, AR, video, audio, ERC-721's and ERC-1155's, and POAPs
> 
> For support or assistance, email us at support@rainbow.me
> 
> For feedback or feature requests, email us at hello@rainbow.me or find us on Twitter @rainbowdotme

</details>

<details><summary> 🛡️ Trust</summary>

### Name
> Trust: Crypto & Bitcoin Wallet

### Short description
> Binance Official Crypto Wallet Store Bitcoin, Ethereum, TRX, XRP, BNB, USDT, NFT

### Full description
> Trust Wallet is a multi-chain self-custody cryptocurrency wallet and secure gateway to thousands of Web3 decentralized applications (dApps).
> 
> Trust Wallet is already “trusted” and used by 60+ million people, and is the easiest way to store, send and receive digital assets, manage your NFT collection, explore DeFi, GameFi, and the metaverse.
> 
> As a secure self-custody crypto wallet, Trust Wallet allows you to take complete control of your crypto assets. That means no one can freeze your funds, halt your withdrawals, or take your funds without your permission.
> 
> Trust Wallet supports 8+ million digital assets, non-fungible tokens (NFTs), 70+ blockchains, and allows you to connect safely to thousands of Web3 dApps.
> 
> So what can you do with dApps?
> 
> Swap coins and tokens across different blockchains, explore and manage your favorite NFT collections, earn rewards on your crypto, play popular Web3 games, access the metaverse, and everything in between.
> 
> With the Trust Wallet Mobile App, you get:
> 
> A SECURE SELF-CUSTODY CRYPTO WALLET
> 
> Instantly turn your mobile device into a powerful self-custody Web3 wallet and gateway to thousands of dApps. Trust Wallet also supports WalletConnect v2.
> With a self-custody wallet like Trust Wallet, you’re always in complete control of your digital assets. Use the app as your bitcoin wallet, NFT wallet, or crypto wallet for millions of assets.
> 
> INDUSTRY-LEADING SECURITY
> 
> Secure login and built-in security features that prevent unauthorized access to your assets.
> Your private keys are safely stored on your device and are strongly encrypted with an AES algorithm. Also, we do not collect any contact information or personal details.
> 
> MULTI-CHAIN FUNCTIONALITY & THE LARGEST TOKEN SUPPORT
> 
> Trust Wallet supports 70+ blockchains, and 8+ million assets including Bitcoin (BTC), Ethereum (ETH), Solana (SOL), (XRP) XRP, Cardano (ADA), Bitcoin Cash (BCH), BNB (BNB), Polygon (MATIC), Avalanche (AVAX), zkEVM, zkSync Era, and more.
> Manage NFTs from different blockchains easily in one place
> 
> THE MOST EASY-TO-USE CRYPTO WALLET
> 
> Buy & Sell Bitcoin and cryptocurrencies via 3rd party fiat payment processors as well as swap and stake cryptocurrency securely – all without leaving the app.
> Helpful integrations like Coinbase Pay and Binance Pay to deposit crypto seamlessly from your exchange account in just a few clicks.
> Leverage our integrated tax feature, which is an optional tool for those who want to report their taxes without the usual complexity of manually adding transactions and wallets.
> Take advantage of our dApp browser and “plug and play” network auto-detect feature, which makes connecting to dApps across different blockchains quick and easy.
> 
> ADVANCED FEATURES FOR CRYPTO TECHIES
> 
> Dive into more advanced features (if you consider yourself a crypto techie) like adding custom tokens and adjusting your node settings.
> Use “watch addresses” to monitor all your crypto wallets in one place.
> 
> A WALLET USED BY 60+ MILLION PEOPLE
> 
> Trust Wallet is used by over 60 million people worldwide and supports multiple languages.
> Securely store, send and receive crypto from family and friends, or your exchange account.
> 
> Ready to turn your mobile device into your go-to Bitcoin Wallet, NFT Wallet, and crypto wallet for thousands of other digital assets?
> 
> If you’re already a Trust Wallet Browser Extension user, you can quickly import your wallet to move between mobile and desktop seamlessly — and if you’re new to Trust Wallet, we’ll help you get started quickly and securely.
> 
> Join 60+ million people who already trust our Wallet — get Trust Wallet today!
> 
> Trust Wallet is built with, and for our community. Have an idea, want to share feedback, or need support? Reach out to us here: support@trustwallet.com and follow us on Twitter: @TrustWallet
</details>

**Comment by nop33** [comment]
Regarding iOS, the next step might be to go for TestFlight release which allows up to 10'000 users: https://docs.expo.dev/guides/sharing-preview-releases/#testflight

**Comment by nop33** [comment]
To make the TestFlight release available in France, we need to submit a "French encryption declaration" to Apple Store https://developer.apple.com/help/app-store-connect/reference/export-compliance-documentation-for-encryption/

<img width="688" alt="image" src="https://github.com/alephium/mobile-wallet/assets/1579899/24c2722a-81bb-4e19-b29a-68b97e060bb5">

**Comment by mvaivre** [comment]
@VDAODAO Let's work on the description texts together next week? For the beta, we'll go for some simple placeholder texts.

**Comment by nop33** [comment]
Beta releases are out!

- https://play.google.com/store/apps/details?id=org.alephium.wallet
- https://testflight.apple.com/join/oRHkgVPU

Closing issue.
