### ISSUE TITLE
Make it harder to delete a wallet

### ISSUE THREAD

**Issue by mvaivre** [alephium/mobile-wallet#298]
Once the user tap on "Delete wallet" we could open a bottom modal saying "Are you sure?".

To validate the action, the user should type the wallet name in an input, then validate (bottom button).

**Comment by mvaivre** [comment]
Actually this is an easy one. I'd rather have this for the v1. WDYT @nop33?

**Comment by nop33** [comment]
Fine by me. Are you on it?

**Comment by mvaivre** [comment]
yes

**Comment by nop33** [comment]
Done, closing.

**Comment by nit27** [comment]
I personally think we should call it as "Remove the wallet" because we cannot "delete" a wallet address in blockchain :D  
At the warning notification, we can quickly remind people that they can import this wallet again by their *secret phrases* 👀

**Comment by nop33** [comment]
Interesting thoughts. I am not convinced, however. We are "deleting" the mnemonic from the device's secure storage, and all the metadata stored. It has nothing to do with the blockchain :)

But I like your idea of letting the user know they can import it again. I think we could adjust some texts, for example:

<img width="487" alt="image" src="https://github.com/alephium/mobile-wallet/assets/1579899/8b9dee54-78b9-4ffe-9e4b-074c81cf1e2e">

**Comment by nit27** [comment]
It's fine. By the way, I've just looked at the Desktop and Extension wallets. I prefer the explaination of Desktop Wallet as it simple enough to "reduce to the max" :-D. The screenshot you provided had 3 sentences, so I think it has too much words😅 (but it's clear)  *(maybe I am a disorder reader 🥶)*

<img width="601" alt="Screenshot 2023-10-19 at 2 38 59 PM" src="https://github.com/alephium/mobile-wallet/assets/95131051/6a6a70d6-fd8d-4dce-8dd8-12b41d377390">
<img width="360" alt="Screenshot 2023-10-19 at 2 39 40 PM" src="https://github.com/alephium/mobile-wallet/assets/95131051/abafd9d6-4ed1-4dbf-ab12-bce597af0e70">
