### ISSUE TITLE
Allow network switching by tapping on network badge

### ISSUE THREAD

**Issue by nop33** [alephium/mobile-wallet#302]
This was requested by Thiago, and it's something I also had in mind. Tapping on the network badge can open the bottom modal with the 3 network options.

With this, I would also like to take the opportunity to move the custom network settings to their own screen, instead of having them inside the bottom modal. The reason is that the scrollable modal with an active keyboard is still not working very well.

**Comment by mvaivre** [comment]
Yeah let's do that. 


PS: I would love to make the modal work with the keyboard..!
