### ISSUE TITLE
French encryption declaration approval form

### ISSUE THREAD

**Issue by nop33** [alephium/mobile-wallet#311]
To make our app available in France, we need to:
- ~~figure out how to create a "French encryption declaration approval form".~~
- ~~upload it on Apple Store~~

Here's some more info about it: https://gist.github.com/chrisballinger/7239932

The form is probably this one, but I am not sure: https://www.ssi.gouv.fr/uploads/2015/03/ANNEXE-I.pdf

<img width="691" alt="image" src="https://github.com/alephium/mobile-wallet/assets/1579899/6a5c4497-29e3-4e28-9916-19208efcc258">
<img width="676" alt="image" src="https://github.com/alephium/mobile-wallet/assets/1579899/cd59de28-c3bd-450b-97a6-167bdd492b77">

**Comment by MaudSimon** [comment]
- https://cryptomator.org/blog/2016/06/16/indepth-french-app-store/

**Comment by nop33** [comment]
We agreed that we can set `ITSAppUsesNonExemptEncryption` to `false`.

Reasoning:
> We are not using anything special, so there should be a way to publish the app as easy as normal apps

More info:

> Typically, the use of encryption that’s built into the operating system—for example, when your app makes HTTPS connections using URLSession—is exempt from export documentation upload requirements, whereas the use of proprietary encryption is not. To determine whether your use of encryption is considered exempt, see [Determine your export compliance requirements](https://help.apple.com/app-store-connect/#/dev63c95e436).

https://developer.apple.com/documentation/security/complying_with_encryption_export_regulations
