### ISSUE TITLE
Connect to dApps in mobile browsers through deep linking

### ISSUE THREAD

**Issue by diomark** [alephium/mobile-wallet#327]
**Describe the bug**
Trying to open the dapps natively (from chrome browser in android), then selecting walletconnect and clicking mobile/connect  shows list of wallets, but alephium wallet isn't on that list. The scanner works, but it's impossible to scan a qr code from same device.

**To Reproduce**
1. Go to walph.io in chrome mobile browser
2. Click on connect
3. Select WalletConnect
4. The 'open with' list that comes up does not include Alephium wallet, so there is no way to select it.

**Expected behavior**
add alephium to list of wallets that pops up. (right now it's showing metamask/other wallets but not alph wallet)

**Screenshots**
<img width="300" src="https://github.com/alephium/mobile-wallet/assets/20622085/3af59a5d-b76f-4864-96bf-c33812f762fb" />

**Environment**
 - Pixel 7 pro / Android 14

**Additional context**
this makes it impossible to access dapps just from the phone. (you can scan a browser from another device, but not on the same phone)

**Comment by ErgoTester** [comment]
seems in issue with all alephium dapps, this isn't a wallet issue tho no ? might be walletconnect issue

**Comment by nop33** [comment]
Hello @diomark and @ErgoTester, thank you for your valuable feedback!

This is not a WalletConnect issue. It is a feature that has not yet been implemented. Currently, you can only connect to dApps by scanning the QR code from another device (laptop/desktop for example).

I will start working on implementing this feature (connecting to dApps on the mobile browser), but to avoid holding the initial release back, this feature might come in the subsequent release (which is going to be as close to the initial one as possible)!
