### ISSUE TITLE
 ERROR  [Error: Could not decrypt the item in SecureStore]

### ISSUE THREAD

**Issue by nop33** [alephium/mobile-wallet#33]
After adding a new fingerprint to my device (without removing the previous one), I cannot anymore launch the app. It gives this error. It doesn't even ask for my fingerprint.

The error happens here: https://github.com/alephium/mobile-wallet/blob/master/src/storage/wallets.ts#L104

Deleting the newly added fingerprint from the device did not solve the issue.

**Comment by portkey-yellow** [comment]
hi @nop33 , did you solve it? The same problem happened to me here.

**Comment by nop33** [comment]
I have not managed to reproduce this since the last message I posted. I have the feeling that it's happening when there's already a secure item in storage and then the storage configuration changes. Try deleting all stored items

**Comment by nop33** [comment]
I followed the same procedure (creating a wallet, enabling biometrics, closing app, adding new fingerprint in my Android device, launching app again, unlocked it) and I did not get this error. Closing issue for now.
