### ISSUE TITLE
Scan address with QR code doesn't work

### ISSUE THREAD

**Issue by nit27** [alephium/mobile-wallet#330]
## Describe the bug
Cannot scan QR code for recipient address.

## To Reproduce
The error happens while I am in the **send asset** progress  
1. Hit *Send*
2. At *Destination*: hit *Scan* -> It doesn't open camera to scan the QR code (see the screenshot below).

## Expected behavior
It should open the iPhone camera in order to scan the QR code.

## Screenshots
![2023-10-18 3 32 11 PM](https://github.com/alephium/mobile-wallet/assets/95131051/80e3f08d-d75b-4bee-986a-cb27a3505c39)

## Environment
 - iOS 17.0.3
 - Version: 0.1.0 (9)

**Additional context**
None.

**Comment by nit27** [comment]
At home page, hit the QR code icon also cause the same issue.

**Comment by nop33** [comment]
Hello @nit27 , thank you for the report!

I see that you used Version: 0.1.0 (9). Could you please update to use the Version: 0.1.0 (11) instead and let us know if the bug persists? You should probably be able to update by opening the same testflight link.

**Comment by nit27** [comment]
Hi @nop33, thanks for let me know the version update. This error is fixed with v0.1.0 (11) perfectly! 

![photo_2023-10-18 10 34 50 PM](https://github.com/alephium/mobile-wallet/assets/95131051/8dd1283b-808e-4dcc-8a22-d72b863c3b8e)

**Comment by nop33** [comment]
Hell yeah 🚀
