### ISSUE TITLE
Wrong indication of the dollar amount in addresses

### ISSUE THREAD

**Issue by MPousse** [alephium/mobile-wallet#353]
**Describe the bug**
Indication of the dollar amount approximately 2x too large in my addresses (the amount in the overview is correct)

**To Reproduce**
1. Send a blocked amount from another wallet (300 alph with duration 3 days blocked)
2. wait 1 minutes (the time of the transaction)
3. go to the Addresses view -> the amount of alph is ok (+300) but the amount of dollars is wrong.
4. go to the Overview view -> all amount are ok.

**Expected behavior**
a good estimation in the Addresses view

**Screenshots**
<img width="296" alt="image" src="https://github.com/alephium/mobile-wallet/assets/85884010/d964faad-a9fe-4c0d-8262-53677f883d97">
today 310 alph < 60$, not 108.39$

**Environment**
 - OS: Android 14
 - Version 0.1.0 (install of 19oct23)

**Comment by nop33** [comment]
You are absolutely right @MPousse! Thanks so much for spotting this! A fix is coming up.
