### ISSUE TITLE
Refactor Selects so that they all use `BottomModals`

### ISSUE THREAD

**Issue by mvaivre** [alephium/mobile-wallet#42]
All selects should use modals coming from the bottom of the screen, like this one :

<img width="353" alt="image" src="https://user-images.githubusercontent.com/6715943/187211513-98308f01-70ca-4c05-8b6c-58fbb67b8146.png">

Those are actually `react-navigation` screens. This raises 2 questions:

1. Should we try to clone / extend this `BottomModal` as a new component, not linked to the navigation stack? This would allow us to simplify our navigation and to allow for local state management.
2. Should we actually list all the selects as screens in our StackNavigator?

**Comment by nop33** [comment]
Done, closing.
