### ISSUE TITLE
Expo's bare workflow: re-evaluate secure storage solutions

### ISSUE THREAD

**Issue by mvaivre** [alephium/mobile-wallet#5]
Design a bullet proof storage strategy. TBD.

Interesting links:

- [React native doc](https://reactnative.dev/docs/security) : good summary on that topic. 
- [Expo's secure store](https://docs.expo.dev/versions/latest/sdk/securestore/) : cross platform key-value store (for light storage), provided by expo.

**Sezame wallet** approach. They're using 2 types of storage strategy :
- [Keychain storage](https://github.com/maze2-org/sezame-wallet/blob/751d6d97f779bd36886079c31cbb55a9bd156876/app/utils/keychain.ts)
- [Encrypted async storage](https://github.com/maze2-org/sezame-wallet/blob/44b038aad1269ba008ef19f49db2f9a6ed1f3385/app/utils/storage/storage.ts)

**Rainbow wallet** seems to be using `react-native-keychain` exclusively
- [keychain.ts](https://github.com/rainbow-me/rainbow/blob/6a55c058461cf909b0c9e6ec02bf79e13ff1d225/src/model/keychain.ts)
- [wallet.ts](https://github.com/rainbow-me/rainbow/blob/6a55c058461cf909b0c9e6ec02bf79e13ff1d225/src/model/wallet.ts)

**Comment by nop33** [comment]
This research summarizes this discussion. I believe we can close this issue. @mvaivre any final thoughts/objections?

https://github.com/orgs/alephium/teams/front-end/discussions/8

**Comment by mvaivre** [comment]
All good on my side! Let's keep the research archived somewhere we can find it, in case we need to dig again one day.
